drop extension if exists "pg_net";

create sequence "public"."games_id_seq";

create sequence "public"."grounds_id_seq";

create sequence "public"."leagues_id_seq";

create sequence "public"."players_id_seq";

create sequence "public"."vsteams_id_seq";


  create table "public"."at_bat_results" (
    "no" bigint generated by default as identity not null,
    "name" character varying,
    "short_name" character varying,
    "display_name" character varying,
    "create_at" timestamp without time zone not null default now(),
    "is_at_bat" boolean,
    "bases" smallint,
    "outs" smallint,
    "with_direction" boolean
      );


alter table "public"."at_bat_results" enable row level security;


  create table "public"."attendance" (
    "team_id" character varying not null,
    "game_id" character varying not null,
    "player_id" character varying not null,
    "attendance_no" smallint,
    "real_attendance_no" smallint,
    "comment" text,
    "helper_count" smallint,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."attendance" enable row level security;


  create table "public"."batting_result_details" (
    "team_id" character varying not null,
    "game_id" character varying not null,
    "player_id" character varying not null,
    "inning_index" smallint not null,
    "at_bat_result_no" smallint,
    "direction_no" smallint,
    "rbi" smallint,
    "create_at" timestamp with time zone default now(),
    "inning" smallint,
    "batting_index" smallint not null
      );


alter table "public"."batting_result_details" enable row level security;


  create table "public"."batting_results" (
    "team_id" character varying not null,
    "game_id" character varying not null,
    "player_id" character varying not null,
    "batting_order" smallint not null,
    "steal" smallint default '0'::smallint,
    "run" smallint default '0'::smallint,
    "df_error" smallint default '0'::smallint,
    "steal_miss" smallint default '0'::smallint,
    "created_at" timestamp with time zone not null default now(),
    "positions" smallint[],
    "batting_index" smallint not null
      );


alter table "public"."batting_results" enable row level security;


  create table "public"."games" (
    "team_id" character varying not null,
    "id" character varying not null default nextval('public.games_id_seq'::regclass),
    "start_datetime" timestamp with time zone not null,
    "league_id" character varying,
    "ground_id" character varying,
    "is_batting_first" boolean,
    "vsteam_id" character varying,
    "status" smallint,
    "remarks" text,
    "game_comment" text,
    "created_at" timestamp with time zone not null default now(),
    "sum_flg" boolean not null,
    "top_points" smallint[],
    "bottom_points" smallint[],
    "innings" smallint[],
    "now_inning" smallint,
    "now_is_top" boolean
      );


alter table "public"."games" enable row level security;


  create table "public"."goals" (
    "team_id" character varying not null,
    "player_id" character varying not null,
    "year" smallint not null,
    "goal_no" bigint not null,
    "goal_value" text,
    "memo" text,
    "created_at" timestamp with time zone not null default now(),
    "sort" smallint
      );


alter table "public"."goals" enable row level security;


  create table "public"."golals_division" (
    "no" bigint generated by default as identity not null,
    "goal_group_no" smallint,
    "goal_name" text,
    "goal_type" smallint,
    "created_at" timestamp with time zone not null default now(),
    "high_goal_flg" boolean,
    "table_name" text,
    "column_name" text
      );


alter table "public"."golals_division" enable row level security;


  create table "public"."grounds" (
    "team_id" character varying not null,
    "id" character varying not null default nextval('public.grounds_id_seq'::regclass),
    "name" text not null,
    "created_at" timestamp with time zone not null default now(),
    "show_flg" boolean not null,
    "sort" smallint not null
      );


alter table "public"."grounds" enable row level security;


  create table "public"."leagues" (
    "team_id" character varying not null,
    "id" character varying not null default (nextval('public.leagues_id_seq'::regclass))::text,
    "name" text not null,
    "show_flg" boolean not null,
    "created_at" timestamp with time zone not null default now(),
    "sort" smallint not null
      );


alter table "public"."leagues" enable row level security;


  create table "public"."myteams" (
    "id" character varying not null,
    "name" text not null,
    "one_name" character varying,
    "team_icon" text,
    "status" boolean not null,
    "create_at" timestamp with time zone default now(),
    "passphrase" text,
    "team_color" text,
    "team_logo" text,
    "top_image" text
      );


alter table "public"."myteams" enable row level security;


  create table "public"."past_players" (
    "team_id" character varying not null,
    "player_id" character varying not null,
    "no" character varying,
    "name" text not null,
    "position" text,
    "throw_hand" character varying,
    "batting_hand" character varying,
    "created_at" timestamp with time zone not null default now(),
    "year" smallint not null,
    "sort" smallint,
    "show_flg" boolean
      );


alter table "public"."past_players" enable row level security;


  create table "public"."pitching_results" (
    "team_id" character varying not null,
    "game_id" character varying not null,
    "pitching_order" smallint not null,
    "innings" smallint default '0'::smallint,
    "outs" smallint default '0'::smallint,
    "runs" smallint default '0'::smallint,
    "walks" smallint default '0'::smallint,
    "hbp" smallint default '0'::smallint,
    "hits" smallint default '0'::smallint,
    "homeruns" smallint default '0'::smallint,
    "created_at" timestamp with time zone not null default now(),
    "is_win_lose" boolean default false,
    "is_hold" boolean default false,
    "is_save" boolean default false,
    "strikeout" smallint default '0'::smallint,
    "player_id" character varying
      );


alter table "public"."pitching_results" enable row level security;


  create table "public"."players" (
    "team_id" character varying not null,
    "id" character varying not null default (nextval('public.players_id_seq'::regclass))::text,
    "no" character varying,
    "name" text not null,
    "position" text,
    "throw_hand" character varying,
    "batting_hand" character varying,
    "comment" text,
    "show_flg" boolean not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "is_player" boolean not null,
    "is_admin" boolean not null,
    "is_manager" boolean not null,
    "sort" smallint,
    "list_image" text,
    "detail_image" text
      );


alter table "public"."players" enable row level security;


  create table "public"."positions" (
    "no" bigint generated by default as identity not null,
    "name" character varying,
    "short_name" character varying,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."positions" enable row level security;


  create table "public"."team_profiles" (
    "team_id" character varying not null,
    "no" smallint not null,
    "q" text,
    "a" text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."team_profiles" enable row level security;


  create table "public"."vsteams" (
    "team_id" character varying not null,
    "id" character varying not null default nextval('public.vsteams_id_seq'::regclass),
    "name" text not null,
    "show_flg" boolean not null,
    "created_at" timestamp with time zone not null default now(),
    "sort" smallint not null,
    "one_name" character varying,
    "icon" text
      );


alter table "public"."vsteams" enable row level security;

alter sequence "public"."games_id_seq" owned by "public"."games"."id";

alter sequence "public"."grounds_id_seq" owned by "public"."grounds"."id";

alter sequence "public"."leagues_id_seq" owned by "public"."leagues"."id";

alter sequence "public"."players_id_seq" owned by "public"."players"."id";

alter sequence "public"."vsteams_id_seq" owned by "public"."vsteams"."id";

CREATE UNIQUE INDEX at_bat_results_pkey ON public.at_bat_results USING btree (no);

CREATE UNIQUE INDEX attendance_pkey ON public.attendance USING btree (team_id, game_id, player_id);

CREATE UNIQUE INDEX batting_result_details_pkey ON public.batting_result_details USING btree (team_id, game_id, inning_index, batting_index);

CREATE UNIQUE INDEX batting_results_pkey ON public.batting_results USING btree (team_id, game_id, batting_index);

CREATE UNIQUE INDEX game_pkey ON public.games USING btree (team_id, id);

CREATE UNIQUE INDEX goals_pkey ON public.goals USING btree (team_id, player_id, year, goal_no);

CREATE UNIQUE INDEX golals_division_pkey ON public.golals_division USING btree (no);

CREATE UNIQUE INDEX grounds_pkey ON public.grounds USING btree (team_id, id);

CREATE UNIQUE INDEX leagues_pkey ON public.leagues USING btree (team_id, id);

CREATE UNIQUE INDEX myteams_pkey ON public.myteams USING btree (id);

CREATE UNIQUE INDEX past_players_pkey ON public.past_players USING btree (team_id, player_id, year);

CREATE UNIQUE INDEX pitching_results_pkey ON public.pitching_results USING btree (team_id, game_id, pitching_order);

CREATE UNIQUE INDEX players_pkey ON public.players USING btree (team_id, id);

CREATE UNIQUE INDEX positions_pkey ON public.positions USING btree (no);

CREATE UNIQUE INDEX team_profiles_pkey ON public.team_profiles USING btree (team_id, no);

CREATE UNIQUE INDEX vsteam_pkey ON public.vsteams USING btree (team_id, id);

alter table "public"."at_bat_results" add constraint "at_bat_results_pkey" PRIMARY KEY using index "at_bat_results_pkey";

alter table "public"."attendance" add constraint "attendance_pkey" PRIMARY KEY using index "attendance_pkey";

alter table "public"."batting_result_details" add constraint "batting_result_details_pkey" PRIMARY KEY using index "batting_result_details_pkey";

alter table "public"."batting_results" add constraint "batting_results_pkey" PRIMARY KEY using index "batting_results_pkey";

alter table "public"."games" add constraint "game_pkey" PRIMARY KEY using index "game_pkey";

alter table "public"."goals" add constraint "goals_pkey" PRIMARY KEY using index "goals_pkey";

alter table "public"."golals_division" add constraint "golals_division_pkey" PRIMARY KEY using index "golals_division_pkey";

alter table "public"."grounds" add constraint "grounds_pkey" PRIMARY KEY using index "grounds_pkey";

alter table "public"."leagues" add constraint "leagues_pkey" PRIMARY KEY using index "leagues_pkey";

alter table "public"."myteams" add constraint "myteams_pkey" PRIMARY KEY using index "myteams_pkey";

alter table "public"."past_players" add constraint "past_players_pkey" PRIMARY KEY using index "past_players_pkey";

alter table "public"."pitching_results" add constraint "pitching_results_pkey" PRIMARY KEY using index "pitching_results_pkey";

alter table "public"."players" add constraint "players_pkey" PRIMARY KEY using index "players_pkey";

alter table "public"."positions" add constraint "positions_pkey" PRIMARY KEY using index "positions_pkey";

alter table "public"."team_profiles" add constraint "team_profiles_pkey" PRIMARY KEY using index "team_profiles_pkey";

alter table "public"."vsteams" add constraint "vsteam_pkey" PRIMARY KEY using index "vsteam_pkey";

alter table "public"."attendance" add constraint "attendance_team_id_game_id_fkey" FOREIGN KEY (team_id, game_id) REFERENCES public.games(team_id, id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."attendance" validate constraint "attendance_team_id_game_id_fkey";

alter table "public"."batting_result_details" add constraint "batting_result_details_at_bat_result_no_fkey" FOREIGN KEY (at_bat_result_no) REFERENCES public.at_bat_results(no) not valid;

alter table "public"."batting_result_details" validate constraint "batting_result_details_at_bat_result_no_fkey";

alter table "public"."batting_result_details" add constraint "batting_result_details_team_id_game_id_batting_index_fkey" FOREIGN KEY (team_id, game_id, batting_index) REFERENCES public.batting_results(team_id, game_id, batting_index) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."batting_result_details" validate constraint "batting_result_details_team_id_game_id_batting_index_fkey";

alter table "public"."batting_results" add constraint "batting_results_duplicate_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.myteams(id) not valid;

alter table "public"."batting_results" validate constraint "batting_results_duplicate_team_id_fkey";

alter table "public"."batting_results" add constraint "batting_results_duplicate_team_id_game_id_fkey" FOREIGN KEY (team_id, game_id) REFERENCES public.games(team_id, id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."batting_results" validate constraint "batting_results_duplicate_team_id_game_id_fkey";

alter table "public"."games" add constraint "game_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.myteams(id) not valid;

alter table "public"."games" validate constraint "game_team_id_fkey";

alter table "public"."games" add constraint "game_team_id_ground_id_fkey" FOREIGN KEY (team_id, ground_id) REFERENCES public.grounds(team_id, id) not valid;

alter table "public"."games" validate constraint "game_team_id_ground_id_fkey";

alter table "public"."games" add constraint "game_team_id_league_id_fkey" FOREIGN KEY (team_id, league_id) REFERENCES public.leagues(team_id, id) not valid;

alter table "public"."games" validate constraint "game_team_id_league_id_fkey";

alter table "public"."games" add constraint "game_team_id_vsteam_id_fkey" FOREIGN KEY (team_id, vsteam_id) REFERENCES public.vsteams(team_id, id) not valid;

alter table "public"."games" validate constraint "game_team_id_vsteam_id_fkey";

alter table "public"."goals" add constraint "goals_goal_no_fkey" FOREIGN KEY (goal_no) REFERENCES public.golals_division(no) not valid;

alter table "public"."goals" validate constraint "goals_goal_no_fkey";

alter table "public"."goals" add constraint "goals_team_id_player_id_fkey" FOREIGN KEY (team_id, player_id) REFERENCES public.players(team_id, id) not valid;

alter table "public"."goals" validate constraint "goals_team_id_player_id_fkey";

alter table "public"."grounds" add constraint "grounds_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.myteams(id) not valid;

alter table "public"."grounds" validate constraint "grounds_team_id_fkey";

alter table "public"."leagues" add constraint "leagues_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.myteams(id) not valid;

alter table "public"."leagues" validate constraint "leagues_team_id_fkey";

alter table "public"."past_players" add constraint "past_players_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.myteams(id) not valid;

alter table "public"."past_players" validate constraint "past_players_team_id_fkey";

alter table "public"."pitching_results" add constraint "pitching_results_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.myteams(id) not valid;

alter table "public"."pitching_results" validate constraint "pitching_results_team_id_fkey";

alter table "public"."pitching_results" add constraint "pitching_results_team_id_game_id_fkey" FOREIGN KEY (team_id, game_id) REFERENCES public.games(team_id, id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."pitching_results" validate constraint "pitching_results_team_id_game_id_fkey";

alter table "public"."players" add constraint "players_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.myteams(id) not valid;

alter table "public"."players" validate constraint "players_team_id_fkey";

alter table "public"."team_profiles" add constraint "team_profiles_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.myteams(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."team_profiles" validate constraint "team_profiles_team_id_fkey";

alter table "public"."vsteams" add constraint "vsteam_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.myteams(id) not valid;

alter table "public"."vsteams" validate constraint "vsteam_team_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_my_team_id()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$SELECT team_id FROM public.players 
  WHERE user_id = auth.uid() 
  LIMIT 1;$function$
;

create materialized view "public"."mv_player_daily_pitching_stats" as  WITH base_stats AS (
         SELECT p.team_id,
            p.player_id,
            g.id AS game_id,
            date(g.start_datetime) AS game_date,
            g.start_datetime,
            (EXTRACT(year FROM g.start_datetime))::integer AS season_year,
            g.league_id,
            l.name AS league_name,
            g.ground_id,
            gr.name AS ground_name,
            g.vsteam_id,
            vs.name AS vsteam_name,
            g.status AS game_status,
            g.sum_flg,
            ((COALESCE((p.innings)::integer, 0) * 3) + COALESCE((p.outs)::integer, 0)) AS outs,
            ((((COALESCE((p.innings)::integer, 0) * 3) + COALESCE((p.outs)::integer, 0)))::numeric / 3.0) AS ip,
            COALESCE((p.hits)::integer, 0) AS h,
            COALESCE((p.walks)::integer, 0) AS bb,
            COALESCE((p.hbp)::integer, 0) AS hbp,
            COALESCE((p.strikeout)::integer, 0) AS so,
            COALESCE((p.runs)::integer, 0) AS er,
            COALESCE((p.homeruns)::integer, 0) AS hr,
                CASE
                    WHEN (p.is_save = true) THEN 1
                    ELSE 0
                END AS sv,
                CASE
                    WHEN (p.is_hold = true) THEN 1
                    ELSE 0
                END AS hld,
                CASE
                    WHEN (g.status = 1) THEN 1
                    ELSE 0
                END AS wins,
                CASE
                    WHEN (g.status = 2) THEN 1
                    ELSE 0
                END AS losses
           FROM (((((public.pitching_results p
             JOIN public.games g ON ((((p.team_id)::text = (g.team_id)::text) AND ((p.game_id)::text = (g.id)::text))))
             JOIN public.players pl ON ((((pl.team_id)::text = (p.team_id)::text) AND ((pl.id)::text = (p.player_id)::text))))
             LEFT JOIN public.leagues l ON ((((l.id)::text = (g.league_id)::text) AND ((l.team_id)::text = (g.team_id)::text))))
             LEFT JOIN public.grounds gr ON ((((gr.id)::text = (g.ground_id)::text) AND ((gr.team_id)::text = (g.team_id)::text))))
             LEFT JOIN public.vsteams vs ON ((((vs.id)::text = (g.vsteam_id)::text) AND ((vs.team_id)::text = (g.team_id)::text))))
          WHERE ((g.sum_flg = true) AND (g.status <> ALL (ARRAY[0, 6])))
        )
 SELECT team_id,
    player_id,
    game_id,
    game_date,
    start_datetime,
    season_year,
    league_id,
    league_name,
    ground_id,
    ground_name,
    vsteam_id,
    vsteam_name,
    game_status,
    sum_flg,
    outs,
    ip,
    h,
    bb,
    hbp,
    so,
    er,
    hr,
    sv,
    hld,
    wins,
    losses,
    sum(outs) OVER w AS cum_outs,
    sum(ip) OVER w AS cum_ip,
    sum(h) OVER w AS cum_h,
    sum(bb) OVER w AS cum_bb,
    sum(so) OVER w AS cum_so,
    sum(er) OVER w AS cum_er,
        CASE
            WHEN (sum(outs) OVER w > 0) THEN round(((((sum(h) OVER w + sum(bb) OVER w))::numeric * 3.0) / (sum(outs) OVER w)::numeric), 3)
            ELSE (0)::numeric
        END AS whip,
        CASE
            WHEN (sum(outs) OVER w > 0) THEN round((((sum(er) OVER w)::numeric * 21.0) / (sum(outs) OVER w)::numeric), 2)
            ELSE 999.99
        END AS era,
        CASE
            WHEN (sum(outs) OVER w > 0) THEN round((((sum(so) OVER w)::numeric * 21.0) / (sum(outs) OVER w)::numeric), 2)
            ELSE (0)::numeric
        END AS k7
   FROM base_stats
  WINDOW w AS (PARTITION BY team_id, player_id ORDER BY start_datetime ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
  ORDER BY start_datetime DESC, player_id;


create materialized view "public"."mv_player_daily_stats" as  WITH batting_lines AS (
         SELECT d.team_id,
            d.player_id,
            g.id AS game_id,
            date(g.start_datetime) AS game_date,
            g.start_datetime,
            (EXTRACT(year FROM g.start_datetime))::integer AS season_year,
            g.league_id,
            l.name AS league_name,
            g.ground_id,
            gr.name AS ground_name,
            g.vsteam_id,
            vs.name AS vsteam_name,
            g.status AS game_status,
            g.sum_flg,
            count(*) AS pa,
            sum(
                CASE
                    WHEN (r.is_at_bat = true) THEN 1
                    ELSE 0
                END) AS ab,
            sum(
                CASE
                    WHEN (r.no = ANY (ARRAY[4, 5, 6, 7])) THEN 1
                    ELSE 0
                END) AS h,
            sum(
                CASE
                    WHEN (r.no = 5) THEN 1
                    ELSE 0
                END) AS d2,
            sum(
                CASE
                    WHEN (r.no = 6) THEN 1
                    ELSE 0
                END) AS t3,
            sum(
                CASE
                    WHEN (r.no = 7) THEN 1
                    ELSE 0
                END) AS hr,
            COALESCE(sum(r.bases), (0)::bigint) AS tb,
            sum(
                CASE
                    WHEN (r.no = ANY (ARRAY[2, 3])) THEN 1
                    ELSE 0
                END) AS bb_hbp,
            sum(
                CASE
                    WHEN (r.no = 10) THEN 1
                    ELSE 0
                END) AS sf,
            sum(
                CASE
                    WHEN (r.no = 11) THEN 1
                    ELSE 0
                END) AS sh,
            sum(
                CASE
                    WHEN (r.no = 1) THEN 1
                    ELSE 0
                END) AS so,
            sum(d.rbi) AS rbi,
            COALESCE(sum(r.outs), (0)::bigint) AS total_outs
           FROM ((((((public.batting_result_details d
             JOIN public.at_bat_results r ON ((d.at_bat_result_no = r.no)))
             JOIN public.games g ON ((((d.game_id)::text = (g.id)::text) AND ((g.team_id)::text = (d.team_id)::text))))
             JOIN public.players p ON ((((p.team_id)::text = (d.team_id)::text) AND ((p.id)::text = (d.player_id)::text))))
             LEFT JOIN public.leagues l ON ((((l.id)::text = (g.league_id)::text) AND ((l.team_id)::text = (d.team_id)::text))))
             LEFT JOIN public.grounds gr ON ((((gr.id)::text = (g.ground_id)::text) AND ((gr.team_id)::text = (d.team_id)::text))))
             LEFT JOIN public.vsteams vs ON ((((vs.id)::text = (g.vsteam_id)::text) AND ((vs.team_id)::text = (d.team_id)::text))))
          WHERE ((g.sum_flg = true) AND (g.status <> ALL (ARRAY[0, 6])))
          GROUP BY d.team_id, d.player_id, g.id, (date(g.start_datetime)), g.start_datetime, (EXTRACT(year FROM g.start_datetime)), g.league_id, l.name, g.ground_id, gr.name, g.vsteam_id, vs.name, g.status, g.sum_flg
        ), running_stats AS (
         SELECT b.team_id,
            b.player_id,
            b.game_id,
            COALESCE(sum(b.steal), (0)::bigint) AS sb,
            COALESCE(sum(b.steal_miss), (0)::bigint) AS cs,
            COALESCE(sum(b.run), (0)::bigint) AS runs,
            COALESCE(sum(b.df_error), (0)::bigint) AS errors
           FROM public.batting_results b
          GROUP BY b.team_id, b.player_id, b.game_id
        ), attendance_stats AS (
         SELECT a.team_id,
            a.player_id,
            a.game_id,
            max(
                CASE
                    WHEN (a.real_attendance_no = 1) THEN 1
                    ELSE 0
                END) AS attended_game
           FROM public.attendance a
          GROUP BY a.team_id, a.player_id, a.game_id
        ), base_stats AS (
         SELECT bl.team_id,
            bl.player_id,
            bl.game_id,
            bl.game_date,
            bl.start_datetime,
            bl.season_year,
            bl.league_id,
            bl.league_name,
            bl.ground_id,
            bl.ground_name,
            bl.vsteam_id,
            bl.vsteam_name,
            bl.game_status,
            bl.sum_flg,
            bl.pa,
            bl.ab,
            bl.h,
            bl.d2,
            bl.t3,
            bl.hr,
            bl.tb,
            bl.bb_hbp,
            bl.sf,
            bl.sh,
            bl.so,
            bl.rbi,
            bl.total_outs,
            COALESCE(rs.sb, (0)::bigint) AS sb,
            COALESCE(rs.cs, (0)::bigint) AS cs,
            COALESCE(rs.runs, (0)::bigint) AS runs,
            COALESCE(rs.errors, (0)::bigint) AS errors,
            COALESCE(att.attended_game, 0) AS attended_game
           FROM ((batting_lines bl
             LEFT JOIN running_stats rs ON ((((rs.team_id)::text = (bl.team_id)::text) AND ((rs.player_id)::text = (bl.player_id)::text) AND ((rs.game_id)::text = (bl.game_id)::text))))
             LEFT JOIN attendance_stats att ON ((((att.team_id)::text = (bl.team_id)::text) AND ((att.player_id)::text = (bl.player_id)::text) AND ((att.game_id)::text = (bl.game_id)::text))))
        )
 SELECT team_id,
    player_id,
    game_id,
    game_date,
    start_datetime,
    season_year,
    league_id,
    league_name,
    ground_id,
    ground_name,
    vsteam_id,
    vsteam_name,
    game_status,
    sum_flg,
    pa,
    ab,
    h,
    d2,
    t3,
    hr,
    tb,
    bb_hbp,
    sf,
    sh,
    so,
    rbi,
    total_outs,
    sb,
    cs,
    runs,
    errors,
    attended_game,
    sum(pa) OVER w AS cum_pa,
    sum(ab) OVER w AS cum_ab,
    sum(h) OVER w AS cum_h,
    sum(tb) OVER w AS cum_tb,
    sum(bb_hbp) OVER w AS cum_bb_hbp,
    sum(sf) OVER w AS cum_sf,
    round((sum(h) OVER w / NULLIF(sum(ab) OVER w, (0)::numeric)), 3) AS avg,
    round(((sum(h) OVER w + sum(bb_hbp) OVER w) / NULLIF(((sum(ab) OVER w + sum(bb_hbp) OVER w) + sum(sf) OVER w), (0)::numeric)), 3) AS obp,
    round((sum(tb) OVER w / NULLIF(sum(ab) OVER w, (0)::numeric)), 3) AS slg,
    (round(((sum(h) OVER w + sum(bb_hbp) OVER w) / NULLIF(((sum(ab) OVER w + sum(bb_hbp) OVER w) + sum(sf) OVER w), (0)::numeric)), 3) + round((sum(tb) OVER w / NULLIF(sum(ab) OVER w, (0)::numeric)), 3)) AS ops
   FROM base_stats
  WINDOW w AS (PARTITION BY team_id, player_id ORDER BY start_datetime ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
  ORDER BY start_datetime DESC, player_id;


CREATE OR REPLACE FUNCTION public.refresh_all_materialized_views()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  PERFORM refresh_player_daily_stats();
  PERFORM refresh_player_daily_pitching_stats();
END;
$function$
;

CREATE OR REPLACE FUNCTION public.refresh_player_daily_pitching_stats()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW mv_player_daily_pitching_stats;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.refresh_player_daily_stats()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW mv_player_daily_stats;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.refresh_player_total_pitching_stats()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW mv_player_total_pitching_stats;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.refresh_player_total_stats()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW mv_player_total_stats;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.refresh_player_yearly_pitching_stats()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW mv_player_yearly_pitching_stats;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.refresh_player_yearly_stats()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW mv_player_yearly_stats;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.refresh_player_yearly_titles()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW mv_player_yearly_titles;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.refresh_team_daily_stats()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW mv_team_daily_stats;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.refresh_team_total_stats()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW mv_team_total_stats;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.refresh_team_yearly_stats()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW mv_team_yearly_stats;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.upsert_game_result(p_team_id character varying, p_game_id character varying, p_batting_result jsonb, p_pitching_result jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
    v_batting_record jsonb;    -- 1人分の打者データ
    v_pitching_record jsonb;    -- 1人分の投手データ
BEGIN
    -- 打者成績を削除
    DELETE FROM batting_result_details
    WHERE team_id = p_team_id
    AND game_id = p_game_id
    ;

    DELETE FROM batting_results
    WHERE team_id = p_team_id
    AND game_id = p_game_id
    ;

    -- 打者成績を登録
    FOR v_batting_record IN SELECT * FROM jsonb_array_elements(p_batting_result)
    LOOP
        INSERT INTO batting_results (
            team_id,
            game_id,
            player_id,
            batting_index,
            batting_order,
            positions,
            run,
            steal,
            steal_miss,
            df_error
        ) VALUES (
            (v_batting_record->>'team_id')::VARCHAR,
            (v_batting_record->>'game_id')::VARCHAR,
            (v_batting_record->>'player_id')::VARCHAR,
            (v_batting_record->>'batting_index')::INT,
            (v_batting_record->>'batting_order')::INT,
            (SELECT ARRAY(
                SELECT x::INT 
                FROM jsonb_array_elements_text(v_batting_record->'pisitions') AS x
            )), 
            (v_batting_record->>'run')::INT,
            (v_batting_record->>'steal')::INT,
            (v_batting_record->>'steal_miss')::INT,
            (v_batting_record->>'df_error')::INT
        );

        INSERT INTO batting_result_details (
            team_id,
            game_id,
            player_id,
            batting_index,
            inning,
            inning_index,
            at_bat_result_no,
            direction_no,
            rbi
        )
        SELECT
            (p_team_id)::VARCHAR,
            (p_game_id)::VARCHAR,
            (v_batting_record->>'player_id')::VARCHAR,
            (v_batting_record->>'batting_index')::INT,
            (d->>'inning')::INT,
            (d->>'inning_index')::INT,
            (d->>'at_bat_result_no')::INT,
            (d->>'direction_no')::INT,
            (d->>'rbi')::INT
        FROM jsonb_array_elements(v_batting_record->'batting_result_details') AS d;
    END LOOP;

    -- 投手成績を削除
    DELETE FROM pitching_results
    WHERE team_id = p_team_id
    AND game_id = p_game_id;

    -- 投手成績を登録
    FOR v_pitching_record IN SELECT * FROM jsonb_array_elements(p_pitching_result)
    LOOP
        INSERT INTO pitching_results (
            team_id,
            game_id,
            player_id,
            pitching_order,
            innings,
            outs,
            runs,
            strikeout,
            walks,
            hbp,
            hits,
            homeruns,
            is_win_lose,
            is_hold,
            is_save
        ) VALUES (
            (v_pitching_record->>'team_id')::VARCHAR,
            (v_pitching_record->>'game_id')::VARCHAR,
            (v_pitching_record->>'player_id')::VARCHAR,
            (v_pitching_record->>'pitching_order')::INT,
            (v_pitching_record->>'innings')::INT,
            (v_pitching_record->>'outs')::INT,
            (v_pitching_record->>'runs')::INT,
            (v_pitching_record->>'strikeout')::INT,
            (v_pitching_record->>'walks')::INT,
            (v_pitching_record->>'hbp')::INT,
            (v_pitching_record->>'hits')::INT,
            (v_pitching_record->>'homeruns')::INT,
            (v_pitching_record->>'is_win_lose')::BOOLEAN,
            (v_pitching_record->>'is_hold')::BOOLEAN,
            (v_pitching_record->>'is_save')::BOOLEAN
        );
    END LOOP;
END;$function$
;

CREATE INDEX idx_mv_player_daily_pitching_stats_player ON public.mv_player_daily_pitching_stats USING btree (player_id, game_date DESC);

CREATE INDEX idx_mv_player_daily_pitching_stats_team ON public.mv_player_daily_pitching_stats USING btree (team_id, game_date DESC);

CREATE INDEX idx_mv_player_daily_pitching_stats_team_ground ON public.mv_player_daily_pitching_stats USING btree (team_id, ground_id, game_date DESC);

CREATE INDEX idx_mv_player_daily_pitching_stats_team_league ON public.mv_player_daily_pitching_stats USING btree (team_id, league_id, game_date DESC);

CREATE INDEX idx_mv_player_daily_pitching_stats_team_player ON public.mv_player_daily_pitching_stats USING btree (team_id, player_id, game_date DESC);

CREATE INDEX idx_mv_player_daily_pitching_stats_team_vsteam ON public.mv_player_daily_pitching_stats USING btree (team_id, vsteam_id, game_date DESC);

CREATE INDEX idx_mv_player_daily_pitching_stats_team_year ON public.mv_player_daily_pitching_stats USING btree (team_id, season_year, game_date DESC);

CREATE INDEX idx_mv_player_daily_stats_player ON public.mv_player_daily_stats USING btree (player_id, game_date DESC);

CREATE INDEX idx_mv_player_daily_stats_team ON public.mv_player_daily_stats USING btree (team_id, game_date DESC);

CREATE INDEX idx_mv_player_daily_stats_team_ground ON public.mv_player_daily_stats USING btree (team_id, ground_id, game_date DESC);

CREATE INDEX idx_mv_player_daily_stats_team_league ON public.mv_player_daily_stats USING btree (team_id, league_id, game_date DESC);

CREATE INDEX idx_mv_player_daily_stats_team_player ON public.mv_player_daily_stats USING btree (team_id, player_id, game_date DESC);

CREATE INDEX idx_mv_player_daily_stats_team_vsteam ON public.mv_player_daily_stats USING btree (team_id, vsteam_id, game_date DESC);

CREATE INDEX idx_mv_player_daily_stats_team_year ON public.mv_player_daily_stats USING btree (team_id, season_year, game_date DESC);

grant delete on table "public"."at_bat_results" to "anon";

grant insert on table "public"."at_bat_results" to "anon";

grant references on table "public"."at_bat_results" to "anon";

grant select on table "public"."at_bat_results" to "anon";

grant trigger on table "public"."at_bat_results" to "anon";

grant truncate on table "public"."at_bat_results" to "anon";

grant update on table "public"."at_bat_results" to "anon";

grant delete on table "public"."at_bat_results" to "authenticated";

grant insert on table "public"."at_bat_results" to "authenticated";

grant references on table "public"."at_bat_results" to "authenticated";

grant select on table "public"."at_bat_results" to "authenticated";

grant trigger on table "public"."at_bat_results" to "authenticated";

grant truncate on table "public"."at_bat_results" to "authenticated";

grant update on table "public"."at_bat_results" to "authenticated";

grant delete on table "public"."at_bat_results" to "service_role";

grant insert on table "public"."at_bat_results" to "service_role";

grant references on table "public"."at_bat_results" to "service_role";

grant select on table "public"."at_bat_results" to "service_role";

grant trigger on table "public"."at_bat_results" to "service_role";

grant truncate on table "public"."at_bat_results" to "service_role";

grant update on table "public"."at_bat_results" to "service_role";

grant delete on table "public"."attendance" to "anon";

grant insert on table "public"."attendance" to "anon";

grant references on table "public"."attendance" to "anon";

grant select on table "public"."attendance" to "anon";

grant trigger on table "public"."attendance" to "anon";

grant truncate on table "public"."attendance" to "anon";

grant update on table "public"."attendance" to "anon";

grant delete on table "public"."attendance" to "authenticated";

grant insert on table "public"."attendance" to "authenticated";

grant references on table "public"."attendance" to "authenticated";

grant select on table "public"."attendance" to "authenticated";

grant trigger on table "public"."attendance" to "authenticated";

grant truncate on table "public"."attendance" to "authenticated";

grant update on table "public"."attendance" to "authenticated";

grant delete on table "public"."attendance" to "service_role";

grant insert on table "public"."attendance" to "service_role";

grant references on table "public"."attendance" to "service_role";

grant select on table "public"."attendance" to "service_role";

grant trigger on table "public"."attendance" to "service_role";

grant truncate on table "public"."attendance" to "service_role";

grant update on table "public"."attendance" to "service_role";

grant delete on table "public"."batting_result_details" to "anon";

grant insert on table "public"."batting_result_details" to "anon";

grant references on table "public"."batting_result_details" to "anon";

grant select on table "public"."batting_result_details" to "anon";

grant trigger on table "public"."batting_result_details" to "anon";

grant truncate on table "public"."batting_result_details" to "anon";

grant update on table "public"."batting_result_details" to "anon";

grant delete on table "public"."batting_result_details" to "authenticated";

grant insert on table "public"."batting_result_details" to "authenticated";

grant references on table "public"."batting_result_details" to "authenticated";

grant select on table "public"."batting_result_details" to "authenticated";

grant trigger on table "public"."batting_result_details" to "authenticated";

grant truncate on table "public"."batting_result_details" to "authenticated";

grant update on table "public"."batting_result_details" to "authenticated";

grant delete on table "public"."batting_result_details" to "service_role";

grant insert on table "public"."batting_result_details" to "service_role";

grant references on table "public"."batting_result_details" to "service_role";

grant select on table "public"."batting_result_details" to "service_role";

grant trigger on table "public"."batting_result_details" to "service_role";

grant truncate on table "public"."batting_result_details" to "service_role";

grant update on table "public"."batting_result_details" to "service_role";

grant delete on table "public"."batting_results" to "anon";

grant insert on table "public"."batting_results" to "anon";

grant references on table "public"."batting_results" to "anon";

grant select on table "public"."batting_results" to "anon";

grant trigger on table "public"."batting_results" to "anon";

grant truncate on table "public"."batting_results" to "anon";

grant update on table "public"."batting_results" to "anon";

grant delete on table "public"."batting_results" to "authenticated";

grant insert on table "public"."batting_results" to "authenticated";

grant references on table "public"."batting_results" to "authenticated";

grant select on table "public"."batting_results" to "authenticated";

grant trigger on table "public"."batting_results" to "authenticated";

grant truncate on table "public"."batting_results" to "authenticated";

grant update on table "public"."batting_results" to "authenticated";

grant delete on table "public"."batting_results" to "service_role";

grant insert on table "public"."batting_results" to "service_role";

grant references on table "public"."batting_results" to "service_role";

grant select on table "public"."batting_results" to "service_role";

grant trigger on table "public"."batting_results" to "service_role";

grant truncate on table "public"."batting_results" to "service_role";

grant update on table "public"."batting_results" to "service_role";

grant delete on table "public"."games" to "anon";

grant insert on table "public"."games" to "anon";

grant references on table "public"."games" to "anon";

grant select on table "public"."games" to "anon";

grant trigger on table "public"."games" to "anon";

grant truncate on table "public"."games" to "anon";

grant update on table "public"."games" to "anon";

grant delete on table "public"."games" to "authenticated";

grant insert on table "public"."games" to "authenticated";

grant references on table "public"."games" to "authenticated";

grant select on table "public"."games" to "authenticated";

grant trigger on table "public"."games" to "authenticated";

grant truncate on table "public"."games" to "authenticated";

grant update on table "public"."games" to "authenticated";

grant delete on table "public"."games" to "service_role";

grant insert on table "public"."games" to "service_role";

grant references on table "public"."games" to "service_role";

grant select on table "public"."games" to "service_role";

grant trigger on table "public"."games" to "service_role";

grant truncate on table "public"."games" to "service_role";

grant update on table "public"."games" to "service_role";

grant delete on table "public"."goals" to "anon";

grant insert on table "public"."goals" to "anon";

grant references on table "public"."goals" to "anon";

grant select on table "public"."goals" to "anon";

grant trigger on table "public"."goals" to "anon";

grant truncate on table "public"."goals" to "anon";

grant update on table "public"."goals" to "anon";

grant delete on table "public"."goals" to "authenticated";

grant insert on table "public"."goals" to "authenticated";

grant references on table "public"."goals" to "authenticated";

grant select on table "public"."goals" to "authenticated";

grant trigger on table "public"."goals" to "authenticated";

grant truncate on table "public"."goals" to "authenticated";

grant update on table "public"."goals" to "authenticated";

grant delete on table "public"."goals" to "service_role";

grant insert on table "public"."goals" to "service_role";

grant references on table "public"."goals" to "service_role";

grant select on table "public"."goals" to "service_role";

grant trigger on table "public"."goals" to "service_role";

grant truncate on table "public"."goals" to "service_role";

grant update on table "public"."goals" to "service_role";

grant delete on table "public"."golals_division" to "anon";

grant insert on table "public"."golals_division" to "anon";

grant references on table "public"."golals_division" to "anon";

grant select on table "public"."golals_division" to "anon";

grant trigger on table "public"."golals_division" to "anon";

grant truncate on table "public"."golals_division" to "anon";

grant update on table "public"."golals_division" to "anon";

grant delete on table "public"."golals_division" to "authenticated";

grant insert on table "public"."golals_division" to "authenticated";

grant references on table "public"."golals_division" to "authenticated";

grant select on table "public"."golals_division" to "authenticated";

grant trigger on table "public"."golals_division" to "authenticated";

grant truncate on table "public"."golals_division" to "authenticated";

grant update on table "public"."golals_division" to "authenticated";

grant delete on table "public"."golals_division" to "service_role";

grant insert on table "public"."golals_division" to "service_role";

grant references on table "public"."golals_division" to "service_role";

grant select on table "public"."golals_division" to "service_role";

grant trigger on table "public"."golals_division" to "service_role";

grant truncate on table "public"."golals_division" to "service_role";

grant update on table "public"."golals_division" to "service_role";

grant delete on table "public"."grounds" to "anon";

grant insert on table "public"."grounds" to "anon";

grant references on table "public"."grounds" to "anon";

grant select on table "public"."grounds" to "anon";

grant trigger on table "public"."grounds" to "anon";

grant truncate on table "public"."grounds" to "anon";

grant update on table "public"."grounds" to "anon";

grant delete on table "public"."grounds" to "authenticated";

grant insert on table "public"."grounds" to "authenticated";

grant references on table "public"."grounds" to "authenticated";

grant select on table "public"."grounds" to "authenticated";

grant trigger on table "public"."grounds" to "authenticated";

grant truncate on table "public"."grounds" to "authenticated";

grant update on table "public"."grounds" to "authenticated";

grant delete on table "public"."grounds" to "service_role";

grant insert on table "public"."grounds" to "service_role";

grant references on table "public"."grounds" to "service_role";

grant select on table "public"."grounds" to "service_role";

grant trigger on table "public"."grounds" to "service_role";

grant truncate on table "public"."grounds" to "service_role";

grant update on table "public"."grounds" to "service_role";

grant delete on table "public"."leagues" to "anon";

grant insert on table "public"."leagues" to "anon";

grant references on table "public"."leagues" to "anon";

grant select on table "public"."leagues" to "anon";

grant trigger on table "public"."leagues" to "anon";

grant truncate on table "public"."leagues" to "anon";

grant update on table "public"."leagues" to "anon";

grant delete on table "public"."leagues" to "authenticated";

grant insert on table "public"."leagues" to "authenticated";

grant references on table "public"."leagues" to "authenticated";

grant select on table "public"."leagues" to "authenticated";

grant trigger on table "public"."leagues" to "authenticated";

grant truncate on table "public"."leagues" to "authenticated";

grant update on table "public"."leagues" to "authenticated";

grant delete on table "public"."leagues" to "service_role";

grant insert on table "public"."leagues" to "service_role";

grant references on table "public"."leagues" to "service_role";

grant select on table "public"."leagues" to "service_role";

grant trigger on table "public"."leagues" to "service_role";

grant truncate on table "public"."leagues" to "service_role";

grant update on table "public"."leagues" to "service_role";

grant delete on table "public"."myteams" to "anon";

grant insert on table "public"."myteams" to "anon";

grant references on table "public"."myteams" to "anon";

grant select on table "public"."myteams" to "anon";

grant trigger on table "public"."myteams" to "anon";

grant truncate on table "public"."myteams" to "anon";

grant update on table "public"."myteams" to "anon";

grant delete on table "public"."myteams" to "authenticated";

grant insert on table "public"."myteams" to "authenticated";

grant references on table "public"."myteams" to "authenticated";

grant select on table "public"."myteams" to "authenticated";

grant trigger on table "public"."myteams" to "authenticated";

grant truncate on table "public"."myteams" to "authenticated";

grant update on table "public"."myteams" to "authenticated";

grant delete on table "public"."myteams" to "service_role";

grant insert on table "public"."myteams" to "service_role";

grant references on table "public"."myteams" to "service_role";

grant select on table "public"."myteams" to "service_role";

grant trigger on table "public"."myteams" to "service_role";

grant truncate on table "public"."myteams" to "service_role";

grant update on table "public"."myteams" to "service_role";

grant delete on table "public"."past_players" to "anon";

grant insert on table "public"."past_players" to "anon";

grant references on table "public"."past_players" to "anon";

grant select on table "public"."past_players" to "anon";

grant trigger on table "public"."past_players" to "anon";

grant truncate on table "public"."past_players" to "anon";

grant update on table "public"."past_players" to "anon";

grant delete on table "public"."past_players" to "authenticated";

grant insert on table "public"."past_players" to "authenticated";

grant references on table "public"."past_players" to "authenticated";

grant select on table "public"."past_players" to "authenticated";

grant trigger on table "public"."past_players" to "authenticated";

grant truncate on table "public"."past_players" to "authenticated";

grant update on table "public"."past_players" to "authenticated";

grant delete on table "public"."past_players" to "service_role";

grant insert on table "public"."past_players" to "service_role";

grant references on table "public"."past_players" to "service_role";

grant select on table "public"."past_players" to "service_role";

grant trigger on table "public"."past_players" to "service_role";

grant truncate on table "public"."past_players" to "service_role";

grant update on table "public"."past_players" to "service_role";

grant delete on table "public"."pitching_results" to "anon";

grant insert on table "public"."pitching_results" to "anon";

grant references on table "public"."pitching_results" to "anon";

grant select on table "public"."pitching_results" to "anon";

grant trigger on table "public"."pitching_results" to "anon";

grant truncate on table "public"."pitching_results" to "anon";

grant update on table "public"."pitching_results" to "anon";

grant delete on table "public"."pitching_results" to "authenticated";

grant insert on table "public"."pitching_results" to "authenticated";

grant references on table "public"."pitching_results" to "authenticated";

grant select on table "public"."pitching_results" to "authenticated";

grant trigger on table "public"."pitching_results" to "authenticated";

grant truncate on table "public"."pitching_results" to "authenticated";

grant update on table "public"."pitching_results" to "authenticated";

grant delete on table "public"."pitching_results" to "service_role";

grant insert on table "public"."pitching_results" to "service_role";

grant references on table "public"."pitching_results" to "service_role";

grant select on table "public"."pitching_results" to "service_role";

grant trigger on table "public"."pitching_results" to "service_role";

grant truncate on table "public"."pitching_results" to "service_role";

grant update on table "public"."pitching_results" to "service_role";

grant delete on table "public"."players" to "anon";

grant insert on table "public"."players" to "anon";

grant references on table "public"."players" to "anon";

grant select on table "public"."players" to "anon";

grant trigger on table "public"."players" to "anon";

grant truncate on table "public"."players" to "anon";

grant update on table "public"."players" to "anon";

grant delete on table "public"."players" to "authenticated";

grant insert on table "public"."players" to "authenticated";

grant references on table "public"."players" to "authenticated";

grant select on table "public"."players" to "authenticated";

grant trigger on table "public"."players" to "authenticated";

grant truncate on table "public"."players" to "authenticated";

grant update on table "public"."players" to "authenticated";

grant delete on table "public"."players" to "service_role";

grant insert on table "public"."players" to "service_role";

grant references on table "public"."players" to "service_role";

grant select on table "public"."players" to "service_role";

grant trigger on table "public"."players" to "service_role";

grant truncate on table "public"."players" to "service_role";

grant update on table "public"."players" to "service_role";

grant delete on table "public"."positions" to "anon";

grant insert on table "public"."positions" to "anon";

grant references on table "public"."positions" to "anon";

grant select on table "public"."positions" to "anon";

grant trigger on table "public"."positions" to "anon";

grant truncate on table "public"."positions" to "anon";

grant update on table "public"."positions" to "anon";

grant delete on table "public"."positions" to "authenticated";

grant insert on table "public"."positions" to "authenticated";

grant references on table "public"."positions" to "authenticated";

grant select on table "public"."positions" to "authenticated";

grant trigger on table "public"."positions" to "authenticated";

grant truncate on table "public"."positions" to "authenticated";

grant update on table "public"."positions" to "authenticated";

grant delete on table "public"."positions" to "service_role";

grant insert on table "public"."positions" to "service_role";

grant references on table "public"."positions" to "service_role";

grant select on table "public"."positions" to "service_role";

grant trigger on table "public"."positions" to "service_role";

grant truncate on table "public"."positions" to "service_role";

grant update on table "public"."positions" to "service_role";

grant delete on table "public"."team_profiles" to "anon";

grant insert on table "public"."team_profiles" to "anon";

grant references on table "public"."team_profiles" to "anon";

grant select on table "public"."team_profiles" to "anon";

grant trigger on table "public"."team_profiles" to "anon";

grant truncate on table "public"."team_profiles" to "anon";

grant update on table "public"."team_profiles" to "anon";

grant delete on table "public"."team_profiles" to "authenticated";

grant insert on table "public"."team_profiles" to "authenticated";

grant references on table "public"."team_profiles" to "authenticated";

grant select on table "public"."team_profiles" to "authenticated";

grant trigger on table "public"."team_profiles" to "authenticated";

grant truncate on table "public"."team_profiles" to "authenticated";

grant update on table "public"."team_profiles" to "authenticated";

grant delete on table "public"."team_profiles" to "service_role";

grant insert on table "public"."team_profiles" to "service_role";

grant references on table "public"."team_profiles" to "service_role";

grant select on table "public"."team_profiles" to "service_role";

grant trigger on table "public"."team_profiles" to "service_role";

grant truncate on table "public"."team_profiles" to "service_role";

grant update on table "public"."team_profiles" to "service_role";

grant delete on table "public"."vsteams" to "anon";

grant insert on table "public"."vsteams" to "anon";

grant references on table "public"."vsteams" to "anon";

grant select on table "public"."vsteams" to "anon";

grant trigger on table "public"."vsteams" to "anon";

grant truncate on table "public"."vsteams" to "anon";

grant update on table "public"."vsteams" to "anon";

grant delete on table "public"."vsteams" to "authenticated";

grant insert on table "public"."vsteams" to "authenticated";

grant references on table "public"."vsteams" to "authenticated";

grant select on table "public"."vsteams" to "authenticated";

grant trigger on table "public"."vsteams" to "authenticated";

grant truncate on table "public"."vsteams" to "authenticated";

grant update on table "public"."vsteams" to "authenticated";

grant delete on table "public"."vsteams" to "service_role";

grant insert on table "public"."vsteams" to "service_role";

grant references on table "public"."vsteams" to "service_role";

grant select on table "public"."vsteams" to "service_role";

grant trigger on table "public"."vsteams" to "service_role";

grant truncate on table "public"."vsteams" to "service_role";

grant update on table "public"."vsteams" to "service_role";


  create policy "ALL_SELECT"
  on "public"."at_bat_results"
  as permissive
  for select
  to public
using (true);



  create policy "myteam"
  on "public"."attendance"
  as permissive
  for all
  to authenticated
using (((team_id)::text = public.get_my_team_id()))
with check (((team_id)::text = public.get_my_team_id()));



  create policy "ALL_SELECT"
  on "public"."batting_result_details"
  as permissive
  for select
  to public
using (true);



  create policy "myteam"
  on "public"."batting_result_details"
  as permissive
  for all
  to authenticated
using (((team_id)::text = public.get_my_team_id()))
with check (((team_id)::text = public.get_my_team_id()));



  create policy "ALL_SELECT"
  on "public"."batting_results"
  as permissive
  for select
  to public
using (true);



  create policy "myteam"
  on "public"."batting_results"
  as permissive
  for all
  to authenticated
using (((team_id)::text = public.get_my_team_id()))
with check (((team_id)::text = public.get_my_team_id()));



  create policy "ALL_SELECT"
  on "public"."games"
  as permissive
  for select
  to public
using (true);



  create policy "myteam"
  on "public"."games"
  as permissive
  for all
  to authenticated
using (((team_id)::text = public.get_my_team_id()))
with check (((team_id)::text = public.get_my_team_id()));



  create policy "myteam"
  on "public"."goals"
  as permissive
  for all
  to public
using (((team_id)::text = public.get_my_team_id()))
with check (((team_id)::text = public.get_my_team_id()));



  create policy "ALL_SELECT"
  on "public"."golals_division"
  as permissive
  for select
  to public
using (true);



  create policy "ALL_SELECT"
  on "public"."grounds"
  as permissive
  for select
  to public
using (true);



  create policy "myteam"
  on "public"."grounds"
  as permissive
  for all
  to authenticated
using (((team_id)::text = public.get_my_team_id()))
with check (((team_id)::text = public.get_my_team_id()));



  create policy "ALL_SELECT"
  on "public"."leagues"
  as permissive
  for select
  to public
using (true);



  create policy "myteam"
  on "public"."leagues"
  as permissive
  for all
  to authenticated
using (((team_id)::text = public.get_my_team_id()))
with check (((team_id)::text = public.get_my_team_id()));



  create policy "Allow unauthenticated delete on teams"
  on "public"."myteams"
  as permissive
  for delete
  to public
using (true);



  create policy "Allow unauthenticated insert on teams"
  on "public"."myteams"
  as permissive
  for insert
  to public
with check (true);



  create policy "Allow unauthenticated select on teams"
  on "public"."myteams"
  as permissive
  for select
  to public
using (true);



  create policy "myteam"
  on "public"."myteams"
  as permissive
  for all
  to authenticated
using ((((id)::text = public.get_my_team_id()) AND (status = true)))
with check ((((id)::text = public.get_my_team_id()) AND (status = true)));



  create policy "ALL_SELECT"
  on "public"."past_players"
  as permissive
  for select
  to public
using (true);



  create policy "myteam"
  on "public"."past_players"
  as permissive
  for all
  to public
using (((team_id)::text = public.get_my_team_id()))
with check (((team_id)::text = public.get_my_team_id()));



  create policy "ALL_SELECT"
  on "public"."pitching_results"
  as permissive
  for select
  to public
using (true);



  create policy "myteam"
  on "public"."pitching_results"
  as permissive
  for all
  to authenticated
using (((team_id)::text = public.get_my_team_id()))
with check (((team_id)::text = public.get_my_team_id()));



  create policy "ALL_SELECT"
  on "public"."players"
  as permissive
  for select
  to public
using (true);



  create policy "Allow authenticated users to update own user_id"
  on "public"."players"
  as permissive
  for update
  to public
using ((user_id IS NULL))
with check ((user_id = auth.uid()));



  create policy "Allow unauthenticated insert on players"
  on "public"."players"
  as permissive
  for insert
  to public
with check (true);



  create policy "myteam"
  on "public"."players"
  as permissive
  for all
  to authenticated
using (((team_id)::text = public.get_my_team_id()))
with check (((team_id)::text = public.get_my_team_id()));



  create policy "ALL_SELECT"
  on "public"."positions"
  as permissive
  for select
  to public
using (true);



  create policy "ALL_SELECT"
  on "public"."team_profiles"
  as permissive
  for select
  to public
using (true);



  create policy "myteam"
  on "public"."team_profiles"
  as permissive
  for all
  to authenticated
using (((team_id)::text = public.get_my_team_id()))
with check (((team_id)::text = public.get_my_team_id()));



  create policy "ALL_SELECT"
  on "public"."vsteams"
  as permissive
  for select
  to public
using (true);



  create policy "myteam"
  on "public"."vsteams"
  as permissive
  for all
  to public
using (((team_id)::text = public.get_my_team_id()))
with check (((team_id)::text = public.get_my_team_id()));



  create policy "authenticated 15jb1xy_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'player_images'::text));



  create policy "authenticated 15jb1xy_1"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using ((bucket_id = 'player_images'::text));



  create policy "authenticated 15jb1xy_2"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((bucket_id = 'player_images'::text));



  create policy "authenticated 15jb1xy_3"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using ((bucket_id = 'player_images'::text));



  create policy "full_acccess 13nhyg5_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'team_assets'::text));



  create policy "full_acccess 13nhyg5_1"
  on "storage"."objects"
  as permissive
  for update
  to public
using ((bucket_id = 'team_assets'::text));



  create policy "full_acccess 13nhyg5_2"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'team_assets'::text));



  create policy "full_acccess 13nhyg5_3"
  on "storage"."objects"
  as permissive
  for delete
  to public
using ((bucket_id = 'team_assets'::text));



  create policy "full_acccess cgtdeh_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'vsteams'::text));



  create policy "full_acccess cgtdeh_1"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'vsteams'::text));



  create policy "full_acccess cgtdeh_2"
  on "storage"."objects"
  as permissive
  for update
  to public
using ((bucket_id = 'vsteams'::text));



  create policy "full_acccess cgtdeh_3"
  on "storage"."objects"
  as permissive
  for delete
  to public
using ((bucket_id = 'vsteams'::text));


-- CREATE TRIGGER protect_buckets_delete BEFORE DELETE ON storage.buckets FOR EACH STATEMENT EXECUTE FUNCTION storage.protect_delete();

-- CREATE TRIGGER protect_objects_delete BEFORE DELETE ON storage.objects FOR EACH STATEMENT EXECUTE FUNCTION storage.protect_delete();


